apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: tomcat 
spec: 
  selector: 
    matchLabels: 
      app: tomcat 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: tomcat 
    spec: 
      containers: 
      - name: tomcat 
        image: tamilsaran/kuber:latest 
        ports: 
        - containerPort: 8080
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: tomcat 
spec: 
  selector: 
    app: tomcat 
  ports: 
  - protocol: TCP 
    port: 8080
    targetPort: 8080 
    nodePort: 31000 
  type: NodePort 
